site:
  title: Romme
  url: https://docs.playromme.com
content:
  sources: 
  - url: https://github.com/andrinmeier/romme.git
    branches: HEAD
    start_path: docs
ui: 
  bundle:
    url: ./ui-bundle
    snapshot: true