name: game-logic
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    paths:
    - 'game-logic/**'
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./game-logic
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "16"
        - name: Install dependencies
          run: npm install
        - name: Run the tests
          run: npm test -- --coverage
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v2