name: server
on:
  push:
    paths:
    - 'server/**'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_PROJECT_PATH: server
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: hadolint/hadolint-action@v1.6.0
          with:
            dockerfile: server/Dockerfile
        - uses: superfly/flyctl-actions@1.3
          with:
            args: "deploy"